
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeDetailsWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeDetailsWebServiceSoap {


    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfEmployeeReportsdata
     */
    @WebMethod(operationName = "GetReportData", action = "http://tempuri.org/GetReportData")
    @WebResult(name = "GetReportDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReportData")
    @ResponseWrapper(localName = "GetReportDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReportDataResponse")
    public ArrayOfEmployeeReportsdata getReportData();

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfEmployeeBand
     */
    @WebMethod(operationName = "GetEmployeeBand", action = "http://tempuri.org/GetEmployeeBand")
    @WebResult(name = "GetEmployeeBandResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeBand", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeBand")
    @ResponseWrapper(localName = "GetEmployeeBandResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeBandResponse")
    public ArrayOfEmployeeBand getEmployeeBand();

}
